"""Initial migration

Revision ID: 66d1fa10709b
Revises: 
Create Date: 2024-11-08 15:28:21.143633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d1fa10709b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coldheads',
    sa.Column('coldhead_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('coldhead_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('displacers',
    sa.Column('displacer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('displacer_serial_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('initial_open_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('displacer_id'),
    sa.UniqueConstraint('displacer_serial_number')
    )
    op.create_table('tests',
    sa.Column('test_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('wips',
    sa.Column('wip_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('coldhead_id', sa.Integer(), nullable=False),
    sa.Column('displacer_id', sa.Integer(), nullable=False),
    sa.Column('wip_number', sa.String(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('teardown_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['coldhead_id'], ['coldheads.coldhead_id'], ),
    sa.ForeignKeyConstraint(['displacer_id'], ['displacers.displacer_id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.test_id'], ),
    sa.PrimaryKeyConstraint('wip_id'),
    sa.UniqueConstraint('wip_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wips')
    op.drop_table('tests')
    op.drop_table('displacers')
    op.drop_table('coldheads')
    # ### end Alembic commands ###
